repos:
  - repo: local
    hooks:
      - id: cpp-format
        name: cpp-format
        entry: make cpp-format
        language: system
        pass_filenames: false
      - id: lint-format
        name: py-lint-format
        entry: make py-lint-fix
        language: system
        pass_filenames: false
      - id: native-test
        name: native-test
        entry: make native-test NATIVE_TEST_ARGS="-m"
        language: system
        pass_filenames: false
      - id: py-test
        name: py-test
        entry: make py-test PYTEST_ARGS="-ra"
        language: system
        pass_filenames: false
