#!/usr/bin/env bash
set -e

echo "== Calculator Dev Mode (auto-restart) =="


# entr check
# -----------------------------
if ! command -v entr >/dev/null 2>&1; then
  echo "entr not installed, installing..."

  if command -v dnf >/dev/null 2>&1; then
    sudo dnf install -y entr
  elif command -v apt >/dev/null 2>&1; then
    sudo apt install -y entr
  elif command -v brew >/dev/null 2>&1; then
    brew install entr
  else
    echo "No supported package manager found. Install entr manually."
    exit 1
  fi
else
  echo "entr ready to use"
fi

# venv check
# -----------------------------
if [ ! -d "venv" ]; then
  echo "Creating venv..."
  python -m venv venv
fi

# venv
# -----------------------------
source venv/bin/activate

# dependencies
# -----------------------------
echo "Installing Python deps"
python -m pip install -e ".[dev]"

# formatting
# -----------------------------
echo "Formatting C++"
make cpp-format
make cpp-format-check

echo "Formatting Python"
make py-format
make py-format-check

# native build + tests (CMake + Ninja)
# -----------------------------
make native-test NATIVE_TEST_ARGS=""

# Py-tests
# -----------------------------
echo "Py-test running..."
make py-test PYTEST_ARGS="-ra"


echo "Auto-restart enabled"

# Hot reload
# -----------------------------
find src -name "*.py" | entr -r python -m tcalc
